### PR TITLE
[Typescript] Simple Button

### PR DESCRIPTION
**Pull request by onatm**
This PR adds bunch of things that we need to build components in `typescript` and implements a single `Button` component.

**List of things have been done**

- Added `typescript` and `typings` to dev dependencies
- Added `classnames` to dependencies
- Moved `react` and `react-dom` to peer dependencies
- Added `build:tsc` script to build `typescript` based components

**Note**

I didn't add compiled modules (`/dist` folder) not to overwrite the modules written in `JS`.

**/cc** @edwardcasbon @ninjaferret

### CODE REVIEW

**Comment by santiaago** [comment]
* hc-react will be typescript only (can be use by js apps and ts app)
* clean all javascript code and build deps
* create ts button in components folder
* create an example folder at root level with standalone app (ts or js) that show case the component
* documentation for how to add honeycomb as an example

1. yarn or npm ops
```
yarn add git://github.com/red-gate/honeycomb-web-toolkit
yarn add git://github.com/red-gate/honeycomb-react
``` 

2. add css 

```
import 'honeycomb/dist/honeycomb.css'
```

**Comment by onatm** [comment]
I've spend most of my time today to how to get `typescript` components from `node_modules` 😢  It turned that we should distribute typings along with transpiled components.

We now have an example that covers `Button` components. I'll add documentation which covers how to use `Button` and what are the props we can pass to it.

Also, we are planing to spike to integrate https://github.com/AppraiseQA/appraise in order to give some visual feedback to design people.

We might want to merge this PR after I add the documentation and then we'll look into ci/cd.

**/cc** @santiaago @edwardcasbon @ninjaferret

**Comment by onatm** [comment]
I've added the documentation - I think we are good to go

**Comment by santiaago** [comment]
Looks good @onatm I tested it and it works great thank you 😃

Why do I need to import from `dist` ie `import { Button } from 'honeycomb-react/dist';`

It would be great if we could have it as `import { Button } from 'honeycomb-react';`

what do you think?

**Comment by onatm** [comment]
yay 🎉

**Pull request merged**
