### PR TITLE
Introduce Appraise

### PR DESCRIPTION
**Pull request by onatm**
## What is this PR?
This PR moves examples into `src` folder and documentation next to their relevant components. The documentation has been merged with [`appraise`](http://appraise.qa/) visual test specs. We've introduced `npm` commands for building the demo and running and approving `appraise` test.

## Next steps
- We'll add the documentation how to add and run tests on `appraise`
- We are planning to improve the demo site to have navigation
- Contribution guideline
- PR template
- `Teamcity`

### CODE REVIEW

**Comment by santiaago** [comment]
Looks good @onatm 

Can you add instructions on how to use it in the `Readme` please? 

something like
```
pwd
    /red-gate/honeycomb-react
npm install
npm run build:demo
npm run appraise
```

**Comment by santiaago** [comment]
I am getting an error when running it

```bash
➜ ~/Developer/github/redgate/honeycomb-react (appraise) npm run appraise

> honeycomb-react@0.3.0 appraise /Users/.../Developer/github/redgate/honeycomb-react
> appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results

components/button/README
         ✘      button  1538 pixels differ
         ✘      components/button/README total: 1 failure: 1
✘       Summary total: 1 pages: 1 failure: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! honeycomb-react@0.3.0 appraise: `appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the honeycomb-react@0.3.0 appraise script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-03-02T16_58_59_606Z-debug.log
```

**Comment by santiaago** [comment]
I am still getting an error when running it. I suspect the is a problem between images generated in `mac` and `windows`...

```bash
➜ ~/Developer/github/redgate/honeycomb-react (appraise) npm run appraise
...
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 666 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
components/button/README
         ✘      button  1538 pixels differ
         ✘      components/button/README total: 1 failure: 1
✘       Summary total: 1 pages: 1 failure: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! honeycomb-react@0.3.0 appraise: `npm run build && npm run build:demo && appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the honeycomb-react@0.3.0 appraise script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-03-05T10_20_32_819Z-debug.log
```

**Comment by ninjaferret** [comment]
What are the contents of the `.appraise/results/summary.html` folder showing you? What pixels are different?

We may be able to tweak a few settings but I suspect you are right that there is a difference in the way that a Mac and windows generates images

**Comment by edwardcasbon** [comment]
I too am getting an error running `npm run appraise` on my Mac. Error log is (if it helps):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'appraise' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'preappraise', 'appraise', 'postappraise' ]
5 info lifecycle honeycomb-react@0.3.0~preappraise: honeycomb-react@0.3.0
6 info lifecycle honeycomb-react@0.3.0~appraise: honeycomb-react@0.3.0
7 verbose lifecycle honeycomb-react@0.3.0~appraise: unsafe-perm in lifecycle true
8 verbose lifecycle honeycomb-react@0.3.0~appraise: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/edward.casbon/Websites/honeycomb-react/node_modules/.bin:/Applications/MAMP/bin/php/php7.1.12/bin:/Applications/MAMP/Library/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Applications/MAMP/bin/php/php7.1.12/bin:/Applications/MAMP/Library/bin
9 verbose lifecycle honeycomb-react@0.3.0~appraise: CWD: /Users/edward.casbon/Websites/honeycomb-react
10 silly lifecycle honeycomb-react@0.3.0~appraise: Args: [ '-c',
10 silly lifecycle   'npm run build && npm run build:demo && appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results' ]
11 silly lifecycle honeycomb-react@0.3.0~appraise: Returned: code: 1  signal: null
12 info lifecycle honeycomb-react@0.3.0~appraise: Failed to exec appraise script
13 verbose stack Error: honeycomb-react@0.3.0 appraise: `npm run build && npm run build:demo && appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid honeycomb-react@0.3.0
15 verbose cwd /Users/edward.casbon/Websites/honeycomb-react
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "appraise"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error honeycomb-react@0.3.0 appraise: `npm run build && npm run build:demo && appraise run --examples-dir src --fixtures-dir fixtures --results-dir .appraise/results`
22 error Exit status 1
23 error Failed at the honeycomb-react@0.3.0 appraise script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Re image differences, they're only very slightly different, according to the diff viewer:
 
diff

**Comment by onatm** [comment]
The issue of differences between windows and mac is `Roboto` is rendered differently on both platforms. I believe it can be fixed in `honeycomb-web-toolkit`. If it cannot be fixed, we might wanna decide that `teamcity` output will be the canonical form of our visuals.

**Comment by santiaago** [comment]
should we create an issue in `honeycomb-web-toolkit`? cc: @edwardcasbon @onatm

**Comment by edwardcasbon** [comment]
Ok, so a quick bit of testing between OS's shows that it's not the Roboto font causing the difference.

It may be the font/text aliasing that's causing it. That's my next test.

**Comment by edwardcasbon** [comment]
So, I've removed the font smoothing/antialiasing and there's still a slight difference between the screenshots created on Mac and Windows. I think it's down to how the OS and Chromium combo renders the HTML/CSS. I don't think there's much we can do about it.

As @onatm's mentioned before, we may have to use TeamCity to do the comparison and approval steps.

**Comment by onatm** [comment]
> we may have to use TeamCity to do the comparison and approval steps

I think it would be the most reasonable solution for now

**Comment by onatm** [comment]
We decided to remove `appraise` from dependencies and relevant commands but we keep all work has been done in this PR

**Comment by onatm** [comment]
I've created an issue on `appraise` repo: https://github.com/AppraiseQA/appraise/issues/3

**Pull request merged**
