### PR TITLE
Add ProgressBar and Toggle components

### PR DESCRIPTION
**Pull request by nyctef**
Adds a couple more components to the library. This started out as a test PR to see how to add a new component (ProgressBar) and then we actually needed a new component (Toggle) so I thought I'd try adding it here first. I've also made the demo webpage a bit easier to use.

The Button screenshot has also changed - I assume this is just a difference in the underlying library since it looks like we always pull the latest thing from the honeycomb repo

Questions:

- Are these all the right steps?
- Is there any way to generate the prop types tables, or do we need to type them out manually? Is this worth doing compared to just filling in jsdocs on the typescript types themselves?

### CODE REVIEW

**Comment by nyctef** [comment]
Thinking about it, I should probably try consuming this in figleaf before this PR gets merged - is there an easy way to do that?

**Comment by sai-mohan** [comment]
Can we also have a label to the right hand side of the toggle? e.g. ON and OFF

**Comment by onatm** [comment]
> Thinking about it, I should probably try consuming this in figleaf before this PR gets merged - is there an easy way to do that?

I think the easiest way is to add the components to demo project and test them there.

**Comment by onatm** [comment]
I've just reviewed the code and I've seen that you've already done the demo bit. I think this should work completely fine for our project.

**Comment by nyctef** [comment]
By the demo project do you mean the `*.example.tsx` files? I've added them there (that's also where the screenshots get generated from, right?) but they're not interactive and it's hard to know if they've got the right API

**Comment by nyctef** [comment]
> Can we also have a label to the right hand side of the toggle? e.g. ON and OFF

Currently the "Toggle (checked)" text is where the label would be - does that do the right thing?

**Comment by sai-mohan** [comment]
Yep! That works

**Comment by onatm** [comment]
> By the demo project do you mean the `*.example.tsx` files? I've added them there (that's also where the screenshots get generated from, right?) but they're not interactive and it's hard to know if they've got the right API

you can test their interactiveness by running the demo project with `npm start` command. However, as you said, it is not gonna help with the correctness/usefulness of the API. I believe it is best to c/p these components into our project and see how the API works would be the best option.

**Comment by nyctef** [comment]
> you can test their interactiveness by running the demo project with `npm start` command. However, as you said, it is not gonna help with the correctness/usefulness of the API. I believe it is best to c/p these components into our project and see how the API works would be the best option.

Currently that also doesn't work because they're controlled components with no logic controlling them :P I guess that's solved easily enough by adding some more code to the demo pages, though

I'll have a look at testing out the components in Figleaf and then update this PR

**Comment by lriuui0x0** [comment]
LGTM 👍

**Comment by nyctef** [comment]
> I'll have a look at testing out the components in Figleaf and then update this PR

Turns out installing from a branch of a git repo is relatively straightforward: https://github.com/red-gate/data-masking/compare/toggle-test . Toggle appears to be toggling okay so I think this is good to merge (although we'll need to do a bit more work on our end to cope with the latest honeycomb toolkit version)

**Pull request merged**
